version: 0.2
env:
  variables:
    S3_BUCKET: "demo-hosting-bucket-12"
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install 
   
  build:
    commands:
      - echo Build started on date
      - sudo npm run build
    
  post_build:
     commands:
      - aws s3 sync www/ s3://${S3_BUCKET} #--acl public-read
      - echo Build completed on date
     - aws cloudfront create-invalidation --distribution-id E24OCPOP6LQM4Z --paths "/*"
      - echo "deploying on s3"
artifacts:
  files:
      - '**/*' 
      
      
      










