version: 0.2

phases:
  build:
    commands:
      - echo "Building website..."
      - npm install
      - npm run build
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws cp node_modules/chart.js/dist/docs/samples/ s3://bucket-19-06-2023 --delete

artifacts:
  files:
    - '**/*'
  base-directory: dist
