version: 0.2
env:
  variables:
    S3_BUCKET: "frontend-bucket-19-06-2023"
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install 
   
  build:
    commands:
      - echo Build started on date
      - sudo npm run build
    
  post_build:
     commands:
      - aws s3 sync www/ s3://${S3_BUCKET} 
      - echo Build completed on date
      - aws cloudfront create-invalidation --distribution-id E3I9N71V6P3P30 --paths "/*"
artifacts:
  files:
      - '**/*'
  










