version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - sudo npm install 
  build:
    commands:
      - echo "Building frontend..."
     
  post_build:
    commands:
      - echo "Copying files to S3..."
      - aws s3 cp node_modules/ionicons/dist/ s3://bucket-19-06-2023 --delete
artifacts:
  files:
    - '**/*'
